version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_passw0rd
      POSTGRES_DB: pg_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - .:/app
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://admin:admin_passw0rd@db:5432/pg_database

volumes:
  postgres_data:
