services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_passw0rd
      POSTGRES_DB: pg_database
    volumes:
      - db_data:/var/lib/postgresql/data
    network_mode: host # Use host network mode

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgAdmin@mail.com
      PGADMIN_DEFAULT_PASSWORD: new_pgAdmin_secr3t
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    network_mode: host # Use host network mode

volumes:
  db_data:
  pgadmin-data:
